server:
  port: 80

spring:
  application:
    name: ssmp1
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: defaultDataSource
      url: jdbc:mysql://124.70.36.107:3306/ssm_db?serverTimezone=UTC
      username: ssm_db
      password: asd123

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

